// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:46e50395-d7ac-46ed-bb33-5e0954215c11",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Ve3mTAavq",
    "aws_user_pools_web_client_id": "qbhpms9h7r93e84p8gm71eu9s",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://sg2jwuzmibchjajmtslxeebk6m.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "photoalbumsff395fa1be3d49a2809870f92ec93072100549-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_mobile_analytics_app_id": "c5ae5b96bc324aada239ebb6aa3ca321",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
